<?xml version="1.0" encoding="utf-8"?><Database Name="dbsysca" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=NOT-EDUARDO\SYSCA;Initial Catalog=dbsysca;User ID=sa" SettingsObjectName="sistemaCA.Properties.Settings" SettingsPropertyName="dbsyscaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblaplicacao" Member="tblaplicacaos">
    <Type Name="tblaplicacao">
      <Column Name="id_aplicacao" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="data_cadastro" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="data_aplicacao" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="areaaplicada" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_produtosaplicado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_talhao" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_safra" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_ben" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_funcionario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tblprodutosaplicado_tblaplicacao" Member="tblprodutosaplicado" ThisKey="id_produtosaplicado" OtherKey="id_produtosaplicado" Type="tblprodutosaplicado" IsForeignKey="true" />
      <Association Name="tblfuncionario_tblaplicacao" Member="tblfuncionario" ThisKey="id_funcionario" OtherKey="id_funcionario" Type="tblfuncionario" IsForeignKey="true" />
      <Association Name="tblsafra_tblaplicacao" Member="tblsafra" ThisKey="id_safra" OtherKey="id_safra" Type="tblsafra" IsForeignKey="true" />
      <Association Name="tbltalhao_tblaplicacao" Member="tbltalhao" ThisKey="id_talhao" OtherKey="id_talhao" Type="tbltalhao" IsForeignKey="true" />
      <Association Name="tblben_tblaplicacao" Member="tblben" ThisKey="id_ben" OtherKey="id_ben" Type="tblben" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblcultura" Member="tblculturas">
    <Type Name="tblcultura">
      <Column Name="id_cultura" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nome" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Association Name="tblcultura_tblsafra" Member="tblsafras" ThisKey="id_cultura" OtherKey="id_cultura" Type="tblsafra" />
    </Type>
  </Table>
  <Table Name="dbo.tblproduto" Member="tblprodutos">
    <Type Name="tblproduto">
      <Column Name="id_produto" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nome" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="descricao" Type="System.String" DbType="VarChar(120)" CanBeNull="true" />
      <Column Name="unidade_medida" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="id_tipoproduto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tblproduto_tblprodutosaplicado" Member="tblprodutosaplicados" ThisKey="id_produto" OtherKey="id_produto" Type="tblprodutosaplicado" />
      <Association Name="tbltipoproduto_tblproduto" Member="tbltipoproduto" ThisKey="id_tipoproduto" OtherKey="id_tipoproduto" Type="tbltipoproduto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblitenrevisao" Member="tblitenrevisaos">
    <Type Name="tblitenrevisao">
      <Column Name="id_itenrevisao" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="preco" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Association Name="tblitenrevisao_tblrevisaofutura" Member="tblrevisaofuturas" ThisKey="id_itenrevisao" OtherKey="id_itenrevisao" Type="tblrevisaofutura" />
    </Type>
  </Table>
  <Table Name="dbo.tblprodutosaplicado" Member="tblprodutosaplicados">
    <Type Name="tblprodutosaplicado">
      <Column Name="id_produtosaplicado" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="quantidade" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="preco" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="total" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="id_produto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_fornecedor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tblprodutosaplicado_tblaplicacao" Member="tblaplicacaos" ThisKey="id_produtosaplicado" OtherKey="id_produtosaplicado" Type="tblaplicacao" />
      <Association Name="tblproduto_tblprodutosaplicado" Member="tblproduto" ThisKey="id_produto" OtherKey="id_produto" Type="tblproduto" IsForeignKey="true" />
      <Association Name="tblfornecedor_tblprodutosaplicado" Member="tblfornecedor" ThisKey="id_fornecedor" OtherKey="id_fornecedor" Type="tblfornecedor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblrevisaofuturas" Member="tblrevisaofuturas">
    <Type Name="tblrevisaofutura">
      <Column Name="id_revisao" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="motivo" Type="System.String" DbType="VarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="data_cadastro" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="data_revisao" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="id_ben" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_safra" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_itenrevisao" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tblitenrevisao_tblrevisaofutura" Member="tblitenrevisao" ThisKey="id_itenrevisao" OtherKey="id_itenrevisao" Type="tblitenrevisao" IsForeignKey="true" />
      <Association Name="tblsafra_tblrevisaofutura" Member="tblsafra" ThisKey="id_safra" OtherKey="id_safra" Type="tblsafra" IsForeignKey="true" />
      <Association Name="tblben_tblrevisaofutura" Member="tblben" ThisKey="id_ben" OtherKey="id_ben" Type="tblben" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblusuario" Member="tblusuarios">
    <Type Name="tblusuario">
      <Column Name="id_usuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="login" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="senha" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbltipoproduto" Member="tbltipoprodutos">
    <Type Name="tbltipoproduto">
      <Column Name="id_tipoproduto" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descicao" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Association Name="tbltipoproduto_tblproduto" Member="tblprodutos" ThisKey="id_tipoproduto" OtherKey="id_tipoproduto" Type="tblproduto" />
    </Type>
  </Table>
  <Table Name="dbo.tblfuncionario" Member="tblfuncionarios">
    <Type Name="tblfuncionario">
      <Column Name="id_funcionario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nome" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="funcao" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="ctps" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="data_admissao" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="renumeracao_mensal" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="endere" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="bairro" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="telefone" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="rg" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="cpf" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="obs" Type="System.String" DbType="VarChar(180)" CanBeNull="true" />
      <Column Name="celular" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="sobrenome" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="sexo" Type="System.String" DbType="NChar(2)" CanBeNull="true" />
      <Association Name="tblfuncionario_tblaplicacao" Member="tblaplicacaos" ThisKey="id_funcionario" OtherKey="id_funcionario" Type="tblaplicacao" />
    </Type>
  </Table>
  <Table Name="dbo.tblsafra" Member="tblsafras">
    <Type Name="tblsafra">
      <Column Name="id_safra" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="obs" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="id_cultura" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dataincio" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="descricao" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="datafechamento" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="tblsafra_tblaplicacao" Member="tblaplicacaos" ThisKey="id_safra" OtherKey="id_safra" Type="tblaplicacao" />
      <Association Name="tblsafra_tblrevisaofutura" Member="tblrevisaofuturas" ThisKey="id_safra" OtherKey="id_safra" Type="tblrevisaofutura" />
      <Association Name="tblcultura_tblsafra" Member="tblcultura" ThisKey="id_cultura" OtherKey="id_cultura" Type="tblcultura" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbltalhao" Member="tbltalhaos">
    <Type Name="tbltalhao">
      <Column Name="id_talhao" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descricao" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="localizacao" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="tamanho" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="obs" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="sistemaCutivo" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Association Name="tbltalhao_tblaplicacao" Member="tblaplicacaos" ThisKey="id_talhao" OtherKey="id_talhao" Type="tblaplicacao" />
    </Type>
  </Table>
  <Table Name="dbo.tblbens" Member="tblbens">
    <Type Name="tblben">
      <Column Name="id_ben" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descricao" Type="System.String" DbType="VarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="tipoben" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="codigoControle" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="data_aquisicao" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="preco_aquisicao" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="horimetro_inicial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hodometro_inicial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="placa" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Association Name="tblben_tblaplicacao" Member="tblaplicacaos" ThisKey="id_ben" OtherKey="id_ben" Type="tblaplicacao" />
      <Association Name="tblben_tblrevisaofutura" Member="tblrevisaofuturas" ThisKey="id_ben" OtherKey="id_ben" Type="tblrevisaofutura" />
    </Type>
  </Table>
  <Table Name="dbo.tblfornecedor" Member="tblfornecedors">
    <Type Name="tblfornecedor">
      <Column Name="id_fornecedor" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nomefatasia" Type="System.String" DbType="VarChar(120)" CanBeNull="true" />
      <Column Name="razaosocial" Type="System.String" DbType="VarChar(120)" CanBeNull="true" />
      <Column Name="cpf" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="cnpj" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="endereco" Type="System.String" DbType="VarChar(120)" CanBeNull="true" />
      <Column Name="cidade" Type="System.String" DbType="VarChar(120)" CanBeNull="true" />
      <Column Name="fone" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(120)" CanBeNull="true" />
      <Column Name="obs" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ie" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Association Name="tblfornecedor_tblprodutosaplicado" Member="tblprodutosaplicados" ThisKey="id_fornecedor" OtherKey="id_fornecedor" Type="tblprodutosaplicado" />
    </Type>
  </Table>
  <Function Name="dbo.spListaProduto" Method="spListaProduto">
    <ElementType Name="spListaProdutoResult">
      <Column Name="id_produto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nome" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="descricao" Type="System.String" DbType="VarChar(120)" CanBeNull="true" />
      <Column Name="unidade_medida" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="id_tipoproduto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spCadastarProduto" Method="spCadastarProduto">
    <Parameter Name="nome" Type="System.String" DbType="VarChar(80)" />
    <Parameter Name="descricao" Type="System.String" DbType="VarChar(120)" />
    <Parameter Name="unidade_medida" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="id_tipoproduto" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spDeletarProduto" Method="spDeletarProduto">
    <Parameter Name="idproduto" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spVisualizarProduto" Method="spVisualizarProduto">
    <Parameter Name="idproduto" Type="System.Int32" DbType="Int" />
    <ElementType Name="spVisualizarProdutoResult">
      <Column Name="id_produto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nome" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="descricao" Type="System.String" DbType="VarChar(120)" CanBeNull="true" />
      <Column Name="unidade_medida" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="id_tipoproduto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spAlterarProduto" Method="spAlterarProduto">
    <Parameter Name="idproduto" Type="System.Int32" DbType="Int" />
    <Parameter Name="nome" Type="System.String" DbType="VarChar(80)" />
    <Parameter Name="decricao" Type="System.String" DbType="VarChar(120)" />
    <Parameter Name="unidade_medida" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="Idtipo_produto" Parameter="idtipo_produto" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spPesquisaTipoproduto" Method="spPesquisaTipoproduto">
    <Parameter Name="descricao" Type="System.String" DbType="VarChar(80)" />
    <ElementType Name="spPesquisaTipoprodutoResult">
      <Column Name="id_tipoproduto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descicao" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spListatipoProduto" Method="spListatipoProduto">
    <ElementType Name="spListatipoProdutoResult">
      <Column Name="id_tipoproduto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descicao" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spVisualizarFuncionario" Method="spVisualizarFuncionario">
    <Parameter Name="idfuncionario" Type="System.Int32" DbType="Int" />
    <ElementType Name="spVisualizarFuncionarioResult">
      <Column Name="id_funcionario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nome" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="funcao" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="ctps" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="data_admissao" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="renumeracao_mensal" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="endere" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="bairro" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="telefone" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="rg" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="cpf" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="obs" Type="System.String" DbType="VarChar(180)" CanBeNull="true" />
      <Column Name="celular" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="sobrenome" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="sexo" Type="System.String" DbType="NChar(2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spAlterarFuncionario" Method="spAlterarFuncionario">
    <Parameter Name="idfuncionario" Type="System.Int32" DbType="Int" />
    <Parameter Name="nome" Type="System.String" DbType="VarChar(80)" />
    <Parameter Name="funcao" Type="System.String" DbType="VarChar(80)" />
    <Parameter Name="ctps" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="renumeracao" Type="System.Single" DbType="Real" />
    <Parameter Name="endere" Type="System.String" DbType="VarChar(80)" />
    <Parameter Name="bairro" Type="System.String" DbType="VarChar(80)" />
    <Parameter Name="telefone" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="email" Type="System.String" DbType="VarChar(80)" />
    <Parameter Name="rg" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="cpf" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="obs" Type="System.String" DbType="VarChar(180)" />
    <Parameter Name="celular" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="sobrenome" Type="System.String" DbType="VarChar(80)" />
    <Parameter Name="sexo" Type="System.String" DbType="NChar(2)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spDeletarFuncionario" Method="spDeletarFuncionario">
    <Parameter Name="idfuncionario" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spPesquisaTipoproduto" Method="spPesquisaTipoproduto1">
    <Parameter Name="descricao" Type="System.String" DbType="VarChar(80)" />
    <ElementType Name="spPesquisaTipoprodutoResult1">
      <Column Name="id_tipoproduto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descicao" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spPesquisaFunNome" Method="spPesquisaFunNome">
    <Parameter Name="descricao" Type="System.String" DbType="VarChar(80)" />
    <ElementType Name="spPesquisaFunNomeResult">
      <Column Name="id_funcionario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nome" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="funcao" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="ctps" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="data_admissao" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="renumeracao_mensal" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="endere" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="bairro" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="telefone" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="rg" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="cpf" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="obs" Type="System.String" DbType="VarChar(180)" CanBeNull="true" />
      <Column Name="celular" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="sobrenome" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="sexo" Type="System.String" DbType="NChar(2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spPesquisaFunId" Method="spPesquisaFunId">
    <Parameter Name="descricao" Type="System.Int32" DbType="Int" />
    <ElementType Name="spPesquisaFunIdResult">
      <Column Name="id_funcionario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nome" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="funcao" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="ctps" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="data_admissao" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="renumeracao_mensal" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="endere" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="bairro" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="telefone" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="rg" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="cpf" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="obs" Type="System.String" DbType="VarChar(180)" CanBeNull="true" />
      <Column Name="celular" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="sobrenome" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="sexo" Type="System.String" DbType="NChar(2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spPesquisaFunCPF" Method="spPesquisaFunCPF">
    <Parameter Name="descricao" Type="System.String" DbType="VarChar(15)" />
    <ElementType Name="spPesquisaFunCPFResult">
      <Column Name="id_funcionario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nome" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="funcao" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="ctps" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="data_admissao" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="renumeracao_mensal" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="endere" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="bairro" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="telefone" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="rg" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="cpf" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="obs" Type="System.String" DbType="VarChar(180)" CanBeNull="true" />
      <Column Name="celular" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="sobrenome" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="sexo" Type="System.String" DbType="NChar(2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spCadastrarSafra" Method="spCadastrarSafra">
    <Parameter Name="descricao" Type="System.String" DbType="VarChar(80)" />
    <Parameter Name="status" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="obs" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="dataincio" Type="System.DateTime" DbType="Date" />
    <Parameter Name="id_cultura" Type="System.Int32" DbType="Int" />
    <Parameter Name="datafechamento" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.psListarSafra" Method="psListarSafra">
    <ElementType Name="psListarSafraResult">
      <Column Name="id_safra" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descricao" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="dataincio" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="datafechamento" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="id_cultura" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="obs" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.psVisualizarSafra" Method="psVisualizarSafra">
    <Parameter Name="id_safra" Type="System.Int32" DbType="Int" />
    <ElementType Name="psVisualizarSafraResult">
      <Column Name="id_safra" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descricao" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="dataincio" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="datafechamento" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="id_cultura" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="obs" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spAtualizarSafra" Method="spAtualizarSafra">
    <Parameter Name="idsafra" Type="System.Int32" DbType="Int" />
    <Parameter Name="descricao" Type="System.String" DbType="VarChar(80)" />
    <Parameter Name="status" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="obs" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="dataincio" Type="System.DateTime" DbType="Date" />
    <Parameter Name="id_cultura" Type="System.Int32" DbType="Int" />
    <Parameter Name="datafechamento" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spDeletarSafra" Method="spDeletarSafra">
    <Parameter Name="id_safra" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spPesqiosaTipoCultura" Method="spPesqiosaTipoCultura">
    <Parameter Name="nome" Type="System.String" DbType="VarChar(80)" />
    <ElementType Name="spPesqiosaTipoCulturaResult">
      <Column Name="id_cultura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nome" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spListarTipoCultura" Method="spListarTipoCultura">
    <ElementType Name="spListarTipoCulturaResult">
      <Column Name="id_cultura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nome" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spListarTalhao" Method="spListarTalhao">
    <ElementType Name="spListarTalhaoResult">
      <Column Name="id_talhao" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descricao" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="localizacao" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="tamanho" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="obs" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="sistemaCutivo" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>